### ISSUE TITLE
documentation: missing instructions (and/or session files?) how a session can be defined and started from a display manager

### ISSUE THREAD

**Issue by ppenguin** [instantOS/instantNIX#20]
I just installed `nixos` and directly installed the NUR and `instantnix` system wide (from `/etc/nixos/configuration.nix`), with `lightdm` as the chosen DM. How can  the necessary `xsession` definition be included in such a setup (preferably declaratively so as to enable a consistent default install experience)?

**Comment by con-f-use** [comment]
Glad you tried out instantNIX! Currently, you should start from https://github.com/instantOS/instantNIX/blob/dev/utils/configuration.nix so that the maximum amount of stuff works. I plan to make most of what instantSETTINGS offers configurable via the NixOS module system. Then have an overarching config option like `services.xserver.windowManager.instantnix.enabe = True` that would set defaults and take care of packages to install. But I already have a day job :wink: . To answer your question, [the example NixOS config](https://github.com/instantOS/instantNIX/blob/dev/utils/configuration.nix#L88) has the xsession configured at  around line 88.
Help with the module system would be very appreciated but also testing would be. Also this is not technically a bug.

**Comment by ppenguin** [comment]
Thanks for the quick info, I'll look into it!
Sorry for the bug label, would have been unintended, it was apparently auto-selected and in my haste I hadn't really paid attention to it :wink:  .
